### ISSUE TITLE
How to build programs for PiDrive on external Device

### ISSUE THREAD

**Issue by Offerel** [owncloud/pi-image#11]
I wonder how i can build programs for the Pi on a other external Device, like a vServer or Linux PC for the Pi. Can someone here can help with this?

**Comment by miska** [comment]
Best and easiest option - package it and let your distribution build it for you. Or you can use basic image and qemu. Crosscompilation with dependencies will be hard. I put software I want in my project in OBS, it's quite easy for rpm based distros:

https://build.opensuse.org/project/show/home:-miska-:pidrive

**Comment by oparoz** [comment]
The information is available in the owncloud/ubuntu-snap wiki.
