### ISSUE TITLE
Which owncloud snap repo do we fork?

### ISSUE THREAD

**Issue by oparoz** [owncloud/pi-image#21]
We need to store the ownCloud snap in this repo in order to be able to make modifications and test new features, but which repo should be used as upstream?

This one?: https://github.com/kyrofa/owncloud-snap

@kyrofa @jospoortvliet @enoch85

**Comment by kyrofa** [comment]
Yup, that's the one. The `rolling` branch.

**Comment by oparoz** [comment]
Thanks. I think we should create a new ownCloud repo for it. @jospoortvliet `owncloud/ubuntu-snap`?

**Comment by karlitschek** [comment]
yep. created it https://github.com/owncloud/ubuntu-snap

**Comment by oparoz** [comment]
Thank you @karlitschek
