### ISSUE TITLE
We need instructions on how to flash the images from Windows

### ISSUE THREAD

**Issue by oparoz** [owncloud/pi-image#23]
Some sort of image writing how-to should be added to the wiki.
### How to connect the hardware to a PC

I think we just need to let people know they can connect the drive to a USB3 port to write a new image to disk.
### How to flash the images

We have instructions for Linux, but should have them Windows and OSX as well
1. Recommend tools to uncompress the downloaded images
2. Recommend USB flashing tools which work with these images
3. Document how to both write and expand

---

@kyrofa @enoch85 @jospoortvliet

**Comment by oparoz** [comment]
The image resizing part is problematic... It would be best if performed during the first boot.

**Comment by WaaromZoMoeilijk** [comment]
Have a look at my berrycloud readme for the windows image stuff. Linked to
the raspberry site. Also the resize is easy to fix. Example add to rc.local
remove if successful

Op ma 21 mrt. 2016 14:39 schreef Olivier Paroz notifications@github.com:

> The image resizing part is problematic... It would be best if performed
> during the first boot.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/owncloud/pi-image/issues/23#issuecomment-199282666
> 
> ## 

Met vriendelijke groet,

E. Holm

**Comment by oparoz** [comment]
## Hard drive

### Preparation
1. Connect your HD to both a USB3 port for data and USB2 port for power (via a micro-USB adapter/cable)
2. Extract the writable.img.xz file using ??? (Winrar works)

### Writing the image
1. Download Rufus from https://rufus.akeo.ie/
2. Launch Rufus
3. Click on "Advanced options"
4. Select your HD under "Device". Mine was labelled "NO_LABEL (Disk 1) [1TB]
5. Under "Create a bootable disk using", click on the CD-ROM icon next to it
6. Switch the file type filter from ISO to "\* all files"
7. Select the extracted writable.img which was prepared earlier
8. Click on `Start` and wait a few seconds for the image to be written to the HD
9. Click on `Close`

### Expanding the image

#### As a home user
1.  Download "Paragon Partition Manager Free"
2. Open the app, don't try to resize from the launcher
3. Select your partition (3.5GB) on the external disk
4. Modify the size to the maximum allowed size
5. Apply your changes

#### As a business user
1. Ask your IT guy to do it

**Comment by oparoz** [comment]
@ezraholm50 - Thanks for the info. We can add steps for more than one writer, in case people already have one handy.

> Example add to rc.local remove if successful

Yes, or do a simple test, as people may change their drive sometimes.

**Comment by kyrofa** [comment]
> The image resizing part is problematic... It would be best if performed during the first boot.

It actually should be (if it's not, it's an Ubuntu Core bug). I like to do it myself, but Ubuntu Core should resize the writable partition on boot. Feel free to give that a shot.

**Comment by oparoz** [comment]
Ah, thanks @kyrofa , so maybe the readme should be updated as I was under the impression that without using `write-and-expand` I would be limited to the 3.5GB partition.

**Comment by kyrofa** [comment]
@oparoz oh you're right I did say that didn't I? Okay, let me actually test this and verify that it's working and I'll update it.

**Comment by oparoz** [comment]
There is now a wiki entry which can be completed as needed: https://github.com/owncloud/pi-image/wiki/Flashing-the-image
