### ISSUE TITLE
Support for RPI 3

### ISSUE THREAD

**Issue by SaltyCybernaut** [owncloud/pi-image#26]
What is the time-line for Raspberry Pi 3 support if any?

**Comment by kyrofa** [comment]
No ETA yet; progress is currently being made on u-boot. I can assure you people are working on it, though :smiley: .

**Comment by oparoz** [comment]
@BrianSaia - Don't expect too much improvement though as the limiting factor is currently RAM.

**Comment by miska** [comment]
I would say that for PiDrive Pine64 or Odroid C2 would make much more sense as they have a decent network and can have even more RAM if needed for some reason...

**Comment by jospoortvliet** [comment]
@miska yes, I've asked WD to look into Odroid C2. It is probably going to be compatible with our case, if not let's see if we can make a change to accommodate it.

The Odroid is our best bet in terms of formfactor, community support and price/performance, I think. The ownCloud image would probably be ready for it the moment a Ubuntu Core image would be released for the Odroid, it just needs to be recompiled to 64 bit ;-)
